Adding log configs
gamedoora/gamedoora-aggregation-proxy pull request #10
Opened 2024-03-13 21:38 UTC by picksitquick

## Proposed Changes

  - Added log configs.
  - Made some minor adjustments necessary to run the application.
  - Changes have been tested locally.
  
## Screenshots:

![AggregatorProxy](https://github.com/gamedoora/gamedoora-aggregation-proxy/assets/66877821/0a942ac9-88b7-4b1c-9a06-6aaeb68daebe)

2024-03-14 02:53 UTC, aprajshekhar requested changes

2024-03-14 02:53 UTC, aprajshekhar commented on src/main/java/com/gamedoora/backend/proxy/aggregation/assembler/StudioDataAggregatorAssembler.java
> +@Component
Let's have this as part of a separate PR.

2024-03-14 02:53 UTC, aprajshekhar commented on gamedoora-aggregation-proxy.service
> +Environment="CONFIG_SERVER=http://localhost:8888 LOG_PATH=/var/log/gamedoora/aggregator_proxy_logs"
Let's keep `/var/log/gamedoora` as the path.

2024-03-14 05:54 UTC, picksitquick commented
Changes made, please review

2024-03-16 13:51 UTC, aprajshekhar approved these changes

2024-03-16 13:52 UTC, merged