*DO NOT MERGE* Draft PR
gamedoora/gamedoora-aggregation-proxy pull request #6
Opened 2023-10-05 07:18 UTC by picksitquick

Fixes #5 

## Proposed Changes

  - Adds Roles to User
  - Adds Skills to User
  - Adds Studio to Users
  
Need a draft review before we can take the next steps, Existing Error handlers have been used, if needed new custom error handlers can be made and used.

2023-10-08 12:58 UTC, aprajshekhar commented
Thanks for the PR.

Few suggestions:

1. Please try to avoid single statement if clauses.
2. Create a new exception for validation error.

2023-10-12 09:01 UTC, aprajshekhar requested changes

2023-10-12 09:01 UTC, aprajshekhar commented on pom.xml
The diff is not displaying the changes completely. The distribution management a.k.a maven publish section is not there in the pom.xml of the PR.

2023-12-17 13:16 UTC, aprajshekhar commented
Hi @picksitquick shall I  merge  this PR?

2023-12-17 13:18 UTC, picksitquick commented
> Hi @picksitquick shall I merge this PR?

Yes please

2023-12-17 13:20 UTC, aprajshekhar approved these changes

2023-12-17 13:21 UTC, merged